### ISSUE TITLE
Please add some usage docs or have an example app

### ISSUE THREAD

**Issue by kristianmandrup** [luskhq/redux-ws#8]
Thanks ;)

**Comment by arturmuller** [comment]
Hey Kristian. This was more of a proof of concept — created whilst trying to figure out how to get Websockets working with Redux. We ended up not using this idea in the end. My apologies for not highlighting this in the readme.

Nevertheless I think we could definitely try to open source the solution we ended up with. @pavelvolek what do you think? How much work do you reckon would that be?

**Comment by alejom99** [comment]
I'd be interested to know more about the final solution. Thanks!

**Comment by arturmuller** [comment]
Hey guys. It no longer makes sense to maintain this package because you can now achieve identical functionality directly with [redux-thunk](https://github.com/gaearon/redux-thunk) (as of v2.1.0 — see [injecting a custom argument](https://github.com/gaearon/redux-thunk/tree/v2.1.0#injecting-a-custom-argument) section in the README.md).

Nevertheless, @alejom99, I am planning to write a short blog post about using socket.io with redux sometime in the next month or so. Once it is done I will post a link to it here, in case you (or someone else in the future) is interested.
